### PR TITLE
Final updates for MM MDA compatiblity and NDTiff v3

### PR DESCRIPTION
**Pull request by henrypinkard**

### CODE REVIEW

**Comment by henrypinkard** [comment]
Hey @cgohlke, since I think you may be maintaining a reader for NDTiffs I wanted to point you to this change from NDTiff v2 to v3. The important differences are:

### Differences from version 2

1. In version 2 NDTiff files, even when not using multi-resolution pyramid features, the data were in a `Full resolution` directory. In v3.0 this was eliminated in favor of putting them directly in the top level directory
2. An additional 4 bytes was added to bytes 16-20 of the header of each file containing the minor version of the format, thereby shifting back the summary metadata and it's header by 4 bytes

There's also now a lightweight `ndtiff` pypi package with minimal dependencies, which is also in this repo. If that would be useful to you happy to tell you more

**Comment by cgohlke** [comment]
Thanks for the heads-up.

FWIW, the NDTiffs v3 test files in this repro are corrupted and cannot be read with any common TIFF reader, e.g., with libtiff:

```
tiffinfo ndtiffv3.0_test_NDTiffStack.tif
TIFFFetchDirectory: Sanity check on directory count failed, this is probably not a valid IFD offset.
TIFFReadDirectory: Failed to read directory at offset 330.
```

Am I missing something?

Also, the `ndtiff` package sdist and wheel files on [PyPI](https://pypi.org/project/ndtiff/#files) are missing the `ndtiff` package directory.

**Comment by cgohlke** [comment]
One more thing: I would expect the `x4` pyramid levels in `ndtiffv3.0_stitched_test\Downsampled_x4\ndtiffv3.0_stitched_test_NDTiffStack.tif` to contain images of shape `(14, 14)`, not `(28, 28)`, and level `x8`  to contain images of shape `(7, 7)`, not `(28, 28)`, etc.

**Comment by henrypinkard** [comment]
Ah, yes.  At each level there is a 2x2 downsampling and 2x2 adjacent tiles are combined into one. I can't quite remember why I decided to do it this way...In retrospect it may have been a poor choice

**Comment by cgohlke** [comment]
Another thought: since this repro is the official reference for the NDTiff format, consider providing a comprehensive set of sample files for other implementations to test against, e.g., file format versions 3, 2, 1 and "0", high dimensional datasets. Maybe publish such files on [Zenodo](https://zenodo.org/)? I tried (years ago) to generate files using various versions of MicroManager but that produced corrupted (not according to spec) files. I'd rater test an implementation against "official" reference files.

**Comment by henrypinkard** [comment]
I have the ones in the `test_data` folder in this repo for versions 2 and 3. Do you think just publishing the repo on Zenodo would be sufficient?

For versions 0 and 1, I don't think it is really worth the effort. The format had _very_ limited usage at the time being only used in a Micro-Manager plugin.

**Comment by cgohlke** [comment]
I would prefer less trivial, more comprehensive example files for testing implementations, e.g. a multi-file dataset exceeding 4 GB, or a file containing images of different acquisition modalities, sizes or pixel types (according to the specification that should be possible), or corner cases that I might not be aware of...

**Comment by henrypinkard** [comment]
Okay will do

**Comment by henrypinkard** [comment]
@cgohlke Here's a bunch more tests with corner cases etc


https://doi.org/10.5281/zenodo.7065552

**Comment by cgohlke** [comment]
Thank you! That helps a lot.

**Pull request merged**
