### PR TITLE
Implement axis sorting

### PR DESCRIPTION
**Pull request by ieivanov**
This PR implements sorting of the dataset axes in `PTCZYX` order.

In the original implementation of `Dataset.as_array()`, data is returned in random/unknown dimension order if the `axes=None` argument is not explicitly set. This presents some overhead.

In this PR the array axes are sorted at initialization such that `Dataset.as_array(axes=None)` returns an array in predictable `PTCZYX` order.

Rows and columns are arranged in front, i.e. `RowColCZYX`, and extra axes are placed next to channel, i.e. PTABCZYX if `axes=None`; however, in these cases it is best to specify the axis order explicitly.

@henrypinkard should this order be applied to new axes in `_add_index_entry` as well? How about extending this to the v1 and v2 `ndtiff` file readers?

### CODE REVIEW

**Comment by henrypinkard** [comment]
Nice! That all makes sense and is a good improvement.

> @henrypinkard should this order be applied to new axes in `_add_index_entry` as well?

Yes, I think so. This function is used to get information about a dataset currently being acquired. So its likely that new axes will be added to the dataset from call to call. Not sure if this changes what reasonable default behavior would be. 

> How about extending this to the v1 and v2 `ndtiff` file readers?

Couldn't hurt!

**Comment by henrypinkard** [comment]
I don't think this will cause any problems with the viewer. In theory there is no inherent order to the different axes. If changing the order causes problems than this is a bug to be fixed.

I don't think the order of the scrollbars on the viewer will change. They're probably either alphabetical or appear in the order theyre added. But worth a test to make sure nothing unexpected is happening

**Comment by henrypinkard** [comment]
@ieivanov looks like there are a couple merge conflicts here

**Comment by ieivanov** [comment]
Yeah, this branch fell out of sync. It's OK, I can re-implement the axis sorting on a fresh branch

**Pull request closed without merging**
