### PR TITLE
Removed mmap interface, added file_io supporting arbitrary IO functions

### PR DESCRIPTION
**Pull request by zack-insitro**
# Summary
Enables the use of custom file io functions instead of builtin methods (such as `open`). This is useful in situations where a user loads a dataset from a non-physical resource such as cloud storage. This is implemented using a new `ndtiff.file_io.NDTiffFileIO` class which wraps `open`, `os.listdir`, `os.path.join`, and `os.path.isdir`, enabling the replacement of one or all of these functions with custom methods. For example:

```
from _your_custom_storage_module_ import storage
import ndtiff

file_io = ndtiff.file_io.NDTiffFileIO(open_function=storage.open,
                                      listdir_function=storage.listdir,
                                      path_join_function=storage.pathjoin, 
                                      isdir_function=storage.isdir)

dset = ndtiff.Dataset("s3://bucket_name/path/to/your/dataset", file_io=file_io)
```

By default, the builtin `open` and `os.path` methods are used.

## Changes
- Added `file_io.py`, containing a container `NDTiffFileIO` which allows the user to add custom io commands
- Removed mmap commands in all locations, as they are unneeded according to @henrypinkard. I did have to rework `read_image` in v1 quite a bit, so that's worth reviewing closely.
- Replaced all `open`, `os.path.join`, `os.listdir`, and `os.path.isdir` calls with `file_io` calls
- Added `conftest.py` and added a pytest fixture for test data path
- Added `test_custom_io.py` to test this new interface

## Tests
```
~/repos/NDTiffStorage/python/ndtiff remove_mmap_and_add_support_for_custom_open_function
pyxscope ❯ pytest
============================================ test session starts ============================================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/zack/repos/NDTiffStorage/python, configfile: pyproject.toml
plugins: cov-2.12.1, Flask-Dance-6.1.1, anyio-3.6.2
collected 14 items                                                                                          

test/data_loading_test.py .............                                                               [ 92%]
test/test_custom_io.py .                                                                              [100%]

============================================ 14 passed in 0.57s =============================================
```

### CODE REVIEW

**Comment by henrypinkard** [comment]
Awesome! Everything looks good here. I think this needs to be tested with the image written listener in pycro-manager, but I can take a look at that.

It might be a good improvement if you could write a (perhaps partial) .md file with an example of how to make a custom file_io object that works with a particular cloud storage.

@nicost I think these features might be of interest to you

**Comment by zack-insitro** [comment]
> Awesome! Everything looks good here. I think this needs to be tested with the image written listener in pycro-manager, but I can take a look at that.

Glad to hear. Yeah if you wouldn't mind doing that part that'd be awesome. I'm happy to make fixes if needed.


> It might be a good improvement if you could write a (perhaps partial) .md file with an example of how to make a custom file_io object that works with a particular cloud storage.

Yeah docs make sense. Let me see what I can do without sharing any internal tools...

**Comment by zack-insitro** [comment]
> > It might be a good improvement if you could write a (perhaps partial) .md file with an example of how to make a custom file_io object that works with a particular cloud storage.
> 
> Yeah docs make sense. Let me see what I can do without sharing any internal tools...

Unfortunately I can't strip out the S3 interface code without pulling quite a lot of wrapper code for `boto3` out of our internal tooling :/. I'll add the example above to `README.md`, though. It's almost exactly how you use it if you can find a publicly available interface that provides the same file IO methods as the builtins.

**Comment by henrypinkard** [comment]
Okay no worries, its better than nothing. Tests with image written listener look good!

**Comment by nicost** [comment]
Instructions how to make changes in a PR that someone else submitted are here: https://stackoverflow.com/questions/15530510/how-do-i-push-to-a-pull-request-on-github.

git push <pr-repo.git> <your-local-branch-name>:<pr-branch-name>

It seems important that the branch used to generate the PR is not the main branch and that it is not protected.  I am quite confused how github deals with permissions for these kind of things.

**Comment by zack-insitro** [comment]
> Can you bump the minor version [here](https://github.com/micro-manager/NDTiffStorage/blob/main/python/ndtiff/_version.py). Not sure how to directly edit this on your PR

Bumped!

**Comment by henrypinkard** [comment]
The version number is `major.minor.patch`, where minor changes happen when the API updates (see [semver](https://semver.org/)), so it should be 1.10.0

I just tried the instructions @nicost sent but failed... (thank you for posting it though nico!)

**Comment by zack-insitro** [comment]
> The version number is `major.minor.patch`, where minor changes happen when the API updates (see [semver](https://semver.org/)), so it should be 1.10.0
> 
> I just tried the instructions @nicost sent but failed... (thank you for posting it though nico!)

Ahhh I see. Pushed

**Comment by zack-insitro** [comment]
TYSM @henrypinkard !

**Pull request merged**
